Гриды
htmlacademy-htmlcss/1744101-device-32 pull request #9
Opened 2021-10-30 14:01 UTC by Nikita-Shchurbin

2021-10-30 16:31 UTC, arloktev requested changes

2021-10-30 16:31 UTC, arloktev commented on styles/style.css
> +  box-shadow: inset 0px 40px 0 white;
У тебя есть переменная

2021-10-30 16:31 UTC, arloktev commented on styles/style.css
> +.header-container.container {
Если .container перенести выше всей твоей верстки, то не нужно будет делать более специфичный селектор

2021-10-30 16:31 UTC, arloktev commented on styles/style.css
> +  margin-right: 40px;
А это тебе зачем, если ты задал через grid-gap?

2021-10-30 16:31 UTC, arloktev commented on styles/style.css
> +}*/
А это ты откуда взял?

2021-10-30 16:31 UTC, arloktev commented on styles/style.css
> +  grid-column: 2/4;
А зачем тебе тут grid-ы? Нельзя сделать flex-ами?

2021-10-31 06:40 UTC, Nikita-Shchurbin commented on styles/style.css
> +  margin-right: 40px;
Исправил

2021-10-31 06:42 UTC, Nikita-Shchurbin commented on styles/style.css
> +}*/
Исправил

2021-10-31 06:44 UTC, Nikita-Shchurbin commented on styles/style.css
> +  grid-column: 2/4;
Исправил

2021-10-31 06:55 UTC, Nikita-Shchurbin commented on styles/style.css
> +  box-shadow: inset 0px 40px 0 white;
Тестировал и забыл исправить, исправил

2021-10-31 07:18 UTC, Nikita-Shchurbin commented on styles/style.css
> +.header-container.container {
+

2021-10-31 10:02 UTC, merged